name: quranquest
description: "Quran ChatBot"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_generative_ai: ^0.4.4
  flutter_markdown: ^0.7.3
  logger: ^2.4.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  flutter_riverpod: ^2.5.1
  cloud_firestore: ^5.4.4
  grouped_list: ^6.0.0
  flutter_spinkit: ^5.2.1
  go_router: ^14.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/