// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClIa9qF3U9QbM7gThqqqQ2QPlSLn3kJ5o',
    appId: '1:469859535296:web:ac94d0a682ce8336e32025',
    messagingSenderId: '469859535296',
    projectId: 'quranquest-72cfa',
    authDomain: 'quranquest-72cfa.firebaseapp.com',
    storageBucket: 'quranquest-72cfa.appspot.com',
    measurementId: 'G-EMD9XRMV90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiST8f6SylSO5Iktux4jGER0b3feKAarg',
    appId: '1:469859535296:android:cda66759ccf0d0e8e32025',
    messagingSenderId: '469859535296',
    projectId: 'quranquest-72cfa',
    storageBucket: 'quranquest-72cfa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2KOSZBiB21ghyI2VjTrW7oumPMmTIxuc',
    appId: '1:469859535296:ios:308b79f3bc82223be32025',
    messagingSenderId: '469859535296',
    projectId: 'quranquest-72cfa',
    storageBucket: 'quranquest-72cfa.appspot.com',
    iosBundleId: 'com.example.quranquest',
  );

}